image: node:alpine

lint:
    stage: test
    script:
        - apk add git
        - npm i
        - npx eslint .

pages:
    stage: deploy
    script:
        - apk add git 
        - npm i
        - npx typedoc
    artifacts:
        paths:
            - public
    only:
        - master
