name: docs

on:
  push:
    branches-ignore:
      dependabot/**
  pull_request:
    branches-ignore:
      dependabot/**

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Get Node.js
      uses: actions/setup-node@v1
      with:
        node-version: ">=10.0.0"
    - name: npm install
      run: npm install
      env:
        CI: true
    - name: Set up the environment
      run:
        chmod +x -R ./ci
    - name: Run the tests
      run: ./ci/test.sh
      env:
        CI: true
      if: github.actor != 'tt-bot' && github.actor != 'github-actions'
      continue-on-error: true
    - name: Build documentation
      run: ./ci/build.sh
      env:
        CURRENT_BRANCH: ${{ github.ref }}
        CURRENT_COMMIT: ${{ github.sha }}
        COMMIT_AUTHOR: ${{ github.actor }}
        GIT_ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        CI: true
        CURRENT_REPO: ${{ github.repository }}
      if: github.event_name != 'pull_request' && github.actor != 'tt-bot' && github.actor != 'github-actions'
